### ISSUE TITLE
No matching distribution found for poetry-core>=1.0.0

### ISSUE THREAD

**Issue by robmoorman** [techonomydev/wagtail-email-subscription#10]
Installing via pip requeres core to be installed `No matching distribution found for poetry-core>=1.0.0`

**Comment by robmoorman** [comment]
Installed via pip wheel -r requirements.txt --wheel-dir /opt/dependencies

**Comment by maerteijn** [comment]
@robmoorman Yes, that makes sense as it uses poetry for the build system to create a wheel:
```
[build-system]
requires = ["poetry-core>=1.0.0", " poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
```
A pypi release is planned for next week with a wheel, in the meantime you can add the following as dev dependencies to the project (`requirements.txt`):
```
poetry-core==1.0.3
poetry-dynamic-versioning==0.12.6
```
Then it can build a wheel of the project.

Sorry 🙄

**Comment by robmoorman** [comment]
@maerteijn works for now, thanks!
