### ISSUE TITLE
django.db.utils.IntegrityError: could not create unique index "A mapping field can only be used once for each form" DETAIL:  Key (page_id, mapping)=(10, ) is duplicated.

### ISSUE THREAD

**Issue by robmoorman** [techonomydev/wagtail-email-subscription#11]
The following step in migrations created after adding this package causing an integrity error:

```
        migrations.AddConstraint(
            model_name="formpagefield",
            constraint=models.UniqueConstraint(
                fields=("page", "mapping"),
                name="A mapping field can only be used once for each form",
            ),
        ),
```

There are already added forms in the project this app is added to (but no filled in forms yet).

**Comment by maerteijn** [comment]
@robmoorman This can be considered a thinking error. As the constraint is also applied to empty mappings of course.

Luckily this migration is in each project and not in the models of this package. So it's safe to remove it from your project (see `FormPageField`), and I'll think of another way of not having duplicate mappings per form.

**Comment by maerteijn** [comment]
@robmoorman Fixed this in the contrib package and added a test for it. https://github.com/techonomydev/wagtail-email-subscription/pull/9/commits/5c00ae8cfdd889c718910151a1d5b1a5038c38e3

The https://github.com/techonomydev/wagtail-email-subscription/pull/9 branch will be merged next week
